export const ZUNDA_SPRITE = {
  normal:  new URL("../../assets/characters/zundamon/zundamon-normal.webp", import.meta.url).href,
  hand:    new URL("../../assets/characters/zundamon/zundamon-hand.webp", import.meta.url).href,
  uwame:   new URL("../../assets/characters/zundamon/zundamon-uwame.webp", import.meta.url).href,
  uwame2:  new URL("../../assets/characters/zundamon/zundamon-uwame2.webp", import.meta.url).href,
  uwame3:  new URL("../../assets/characters/zundamon/zundamon-uwame3.webp", import.meta.url).href,
  koshi:   new URL("../../assets/characters/zundamon/zundamon-koshi.webp", import.meta.url).href,
  koshi2:  new URL("../../assets/characters/zundamon/zundamon-koshi2.webp", import.meta.url).href,
  yubi:    new URL("../../assets/characters/zundamon/zundamon-yubi.webp", import.meta.url).href,
  banzai:  new URL("../../assets/characters/zundamon/zundamon-banzai.webp", import.meta.url).href,
  banzai2: new URL("../../assets/characters/zundamon/zundamon-banzai2.webp", import.meta.url).href,
  mufufu:  new URL("../../assets/characters/zundamon/zundamon-mufufu.webp", import.meta.url).href,
  guruguru:new URL("../../assets/characters/zundamon/zundamon-guruguru.webp", import.meta.url).href,
  guruguru2:new URL("../../assets/characters/zundamon/zundamon-guruguru2.webp", import.meta.url).href,
  bikkuri: new URL("../../assets/characters/zundamon/zundamon-bikkuri.webp", import.meta.url).href,
  bikkuri2:new URL("../../assets/characters/zundamon/zundamon-bikkuri2.webp", import.meta.url).href,
  shirome: new URL("../../assets/characters/zundamon/zundamon-shirome.webp", import.meta.url).href,
  tere:    new URL("../../assets/characters/zundamon/zundamon-tere.webp", import.meta.url).href,
  oko:     new URL("../../assets/characters/zundamon/zundamon-oko.webp", import.meta.url).href,
};